### ISSUE TITLE
Switch back to hdmi temporarily?

### ISSUE THREAD

**Issue by pcs3rd** [waveshare/LCD-show#7]
I am making a project where my pi will "dock" and hdmi will get plugged in. is there any way to switch back to hdmi by rebooting?

**Comment by ruivapps** [comment]
I do it all the time. It will modify the /boot/config.txt. on my 3.5 inch display, what it does is to change 
hdmi_mode from 82 (DMT MODE 82 1920X1080 60Hz 16:9) to 87 (DMT mode 87 480x320 59Hz 15:9)
you can either edit it manually or just keep these files around or sed over it. requires reboot to have new mode work.

**Comment by pcs3rd** [comment]
k
closed.
